### ISSUE TITLE
When a cursor moves into a reference, it can't move out of it anymore

### ISSUE THREAD

**Issue by jure** [substance/lens#102]
Arrow keys can no longer move the cursor back out of the reference. Notice the console log increasing the left arrow event keyCode, while nothing happens on screen. Demo below:

![untitled](https://cloud.githubusercontent.com/assets/238667/15359935/cfa96ef8-1d0b-11e6-9d4d-6f5aca24c7a9.gif)

**Comment by dmukhg** [comment]
I have raised this issue before. https://github.com/substance/lens/issues/98 Perhaps we should merge these?

**Comment by jure** [comment]
This is a duplicate of #98, closing. Thanks @schatten!
