### ISSUE TITLE
Initial label is wrong

### ISSUE THREAD

**Issue by michael** [substance/lens#11]
E.g. when i insert a new table before the existing table it gets labeled Table 2, when it should be one. Same happens with image-figures. The labels get corrected as soon as I start the cite workflow.

**Comment by obuchtala** [comment]
Yep. The approach of didAttach is not sufficient.
Actually we want to update the bib not when a bibitem is created or deleted, but when it is shown or hidden.. or maybe both of them.

**Comment by obuchtala** [comment]
Done.
