### ISSUE TITLE
Copy & paste not working when selection spans over caption and paragraph.

### ISSUE THREAD

**Issue by michael** [substance/lens#13]

**Comment by obuchtala** [comment]
Seems to work basically.

@michael Can you narrow it down?

**Comment by michael** [comment]
Interesting. Now it's working with basic text types. However it breaks when there's a figure caption or title involved in the selection.

**Comment by obuchtala** [comment]
Yes I saw that.

**Comment by Integral** [comment]
Interesting in this due to same archivist problems.

**Comment by michael** [comment]
working now.
