### ISSUE TITLE
When a figure citation is copied and pasted in the same doc there's a warning

### ISSUE THREAD

**Issue by michael** [substance/lens#21]
This is actually a nice feature during document production.

**Comment by obuchtala** [comment]
It is because the clipboard document does not contain the bib item.
I think it is ok to have the warning for now.

**Comment by obuchtala** [comment]
Otherwise we would need allow to create a light-weight instance, without the collections.

**Comment by michael** [comment]
I see.. then i will use it now without worries. :)

**Comment by obuchtala** [comment]
I deactivated the updates when it is a clipoard doc.
