### ISSUE TITLE
Selection glitch: When i'm at the very end of a line and insert a citation, the selection looks like this

### ISSUE THREAD

**Issue by michael** [substance/lens#25]
![image](https://cloud.githubusercontent.com/assets/2931/8497937/b5f7ab0e-2181-11e5-9bcc-e9089d20bcd1.png)

**Comment by michael** [comment]
It happens when the label gets separated into two lines. Maybe we could prevent this to happen by making the citation span non-breaking?

**Comment by obuchtala** [comment]
Yep... make it no-break... it feels strange anyways with that breaking.

**Comment by michael** [comment]
Fixed.
