### ISSUE TITLE
Don't rely on globals

### ISSUE THREAD

**Issue by jure** [substance/lens#35]
Please don't rely on global variables, i.e. `i18n` in https://github.com/substance/lens-writer/blob/master/src/components/content_toolbar.js#L32 or `React` in https://github.com/substance/lens-writer/blob/master/src/components/content_toolbar.js#L12

This makes development difficult for people who are integrating lens-writer into different contexts.

**Comment by michael** [comment]
No globals anymore.

**Comment by jure** [comment]
:+1:  awesome!
