### ISSUE TITLE
Read mode is broken?

### ISSUE THREAD

**Issue by larryhengl** [substance/lens#88]
Hi, I'm hitting an error when switching the Lens doc into Read mode (Write mode seems fine). I followed the steps in the README for running the dev sever (clone & install & start).  

Error in browser:
<img width="831" alt="screen shot 2016-02-25 at 8 37 02 am" src="https://cloud.githubusercontent.com/assets/2637196/13326490/011a9a1e-db9b-11e5-92f8-46d23acbf4e5.png">

using
Chrome 48 (mac)
node 5.5.0
npm 3.3.12

**Comment by michael** [comment]
We recursively called the constructor. Don't know how that ever worked. ;)

Fixed via https://github.com/substance/lens/commit/202ab6c20e1a327e4005804753453067420482c4

Thanks for reporting!
